FROM golang:1.19.1-alpine as base

WORKDIR /APP

COPY . .

RUN go mod download

COPY *.go ./
RUN go build -o ./build/rungo .


## Step 2
FROM golang:1.19.1-alpine

WORKDIR /BUILD

COPY --from=base ./APP/build .

CMD [ "./rungo" ]


