FROM golang:1.20.1-alpine  as base

WORKDIR /APP

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o ./build/rungo .


## Step 2
FROM golang:1.20.1-alpine 

WORKDIR /BUILD

COPY --from=base ./APP/build .

CMD [ "./rungo" ]


