FROM tensorflow/tensorflow:2.11.0

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the port on which the application runs

ENV PYTHONUNBUFFERED=1
# Command to run the application
CMD ["python3","-u", "main.py"]