info:
  contact: {}
paths:
  /traces:
    get:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses: {}
      summary: ping example
      tags:
      - Trace
  /traces/{traceid}:
    get:
      description: Return specific Trace with spans tree and detected anomaly
      parameters:
      - description: Trace ID
        in: path
        name: traceid
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get specific Trace
      tags:
      - Trace
swagger: "2.0"
